#[unstable]
#build-std = ["std", "panic_abort"]

[build]
rustflags = [
    "-Ctarget-cpu=native",
    "-Clink-arg=-fuse-ld=lld",
    "-Zthreads=24",
    "-Cforce-frame-pointers=no",
    "-Cprefer-dynamic=no",
    "-Cno-vectorize-loops",
    "-Cno-prepopulate-passes",
]

[alias]
t = "test -- --test-threads=1 --no-capture"
tr = "test --release -- --test-threads=1 --no-capture"
